Options:
    use_cpp: True
    excludes: [examples, test]
    include_dirs: []
    includes: []
    defines: [CONFIG_DEFINED=3, REMOVE=1]
    undefines: [REMOVE]
    arguments: [-D ARR=2]
    files:
      - name: a.h
        includes: [b.h]