Structs:
  - name: config_test
    id: 64
    description: phase tests for config
    enums:
      - member: enumcolor
        values: {1: BLACK, 2: RED, 3: BLUE, 4: YELLOW, 5: WHTIE, 6: GREEN, 7: ORANGE}
      - type: short int
        values: [Zero, One, Two, Three, Four, Five, Six, Seven, Eight, Nine, Ten]
        strict: True # Disable warning if not a valid value
    bitstrings:
      - member: shortbitstring
        1: Group1
        2: [Group2, True, False]
        3-4: [Platform, Win, Linux, Mac, Solaris]
        5-8: Group4
        9-16: Group5
      - member: intbitstring
        1: Group1
        2: [Group2, True, False]
        3-4: [Platform, Win, Linux, Mac, Solaris]
        5-8: Group4
        9-16: Group5
        20-23: [Numbers, One, Two, Three, Four, Five, Six, Seven, Eight, Nine, Ten, Eleven, Twelve, Thirteen, Fourteen, Fifthteen, Zero]
        31: Group7
        32: Group8
      - member: uintbitstring
        1: Group1
        2: [Group2, True, False]
        3-4: [Platform, Win, Linux, Mac, Solaris]
        5-8: Group4
        9-16: Group5
        20-23: [Numbers, One, Two, Three, Four, Five, Six, Seven, Eight, Nine, Ten, Eleven, Twelve, Thirteen, Fourteen, Fifthteen, Zero]
        31: Group7
        32: Group8
      - member: longbitstring
        1: Group1
        2: [Group2, True, False]
        3-4: [Platform, Win, Linux, Mac, Solaris]
        5-8: Group4
        9-16: Group5
        20-23: [Numbers, One, Two, Three, Four, Five, Six, Seven, Eight, Nine, Ten, Eleven, Twelve, Thirteen, Fourteen, Fifthteen, Zero]
        31: Group7
        32: Group8
        47: [Group9, Sant, Usant]
        48-50: [Day, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday, Holiday]
        64: [LastOne, YES, NO]
      - type: unsigned long int
        1: Red
        2: Blue
        3: Green
        4: Yellow
        5: Black
        6: White
        7: Orange
        8: Pink
        63: Brown
        64: OrangePink
    ranges:
      - member: age
        min: 15
        max: 67
    ranges:
      - member: percent
        min: 0
        max: 100